#!/usr/bin/env python3
"""Generate pkg/Kconfig.pkg: one config symbol per repos.txt package."""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "lib"))

from build_pkg import read_repos, symbol_for  # noqa: E402


def main():
    names = read_repos()
    seen = {}
    lines = [
        "# Auto-generated by scripts/gen-pkg-config.py from repos.txt.",
        "# Do not edit; edit repos.txt instead.",
        "",
        'menu "Self-built packages"',
        "",
    ]
    for n in names:
        sym = symbol_for(n)
        if sym in seen:
            raise SystemExit(
                "gen-pkg-config: symbol collision %s (%s vs %s)"
                % (sym, seen[sym], n)
            )
        seen[sym] = n
        lines += ['config %s' % sym, '\tbool "%s"' % n, "\tdefault y", ""]
    lines += ["endmenu", ""]

    out = os.path.join(ROOT, "pkg", "Kconfig.pkg")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    content = "\n".join(lines)
    if os.path.isfile(out):
        with open(out) as f:
            if f.read() == content:
                return  # unchanged
    with open(out, "w") as f:
        f.write(content)
    print("gen-pkg-config: %s (%d packages)" % (out, len(names)))


if __name__ == "__main__":
    main()
